# Project metadata
org.gradle.jvmargs=-Xmx2G

# Minecraft & Fabric
minecraft_version=1.21.1
loader_version=0.16.5
fabric_version=0.104.3+1.21.1

# Mod metadata
maven_group=net.itsn4x.pvprefined
mod_version=1.0.0
archives_base_name=pvprefined

# Dependencies
cloth_config_version=15.0.128
architectury_version=9.2.14
